[package]
name = "test_lib"
version = "0.1.0"
authors = ["mart368b <martinpinholt@hotmail.com>"]
edition = "2018"

[dependencies]
foreignc = {path = "../../foreignc"}
foreignc_derive = {path = "../../foreignc_derive"}

[lib]
crate_type = ["staticlib", "cdylib"]