[package]
name = "lib_test"
version = "0.1.0"
authors = ["mart368b <martinpinholt@hotmail.com>"]
edition = "2018"

[dependencies]
derive_lib = {path = "../derive_lib"}
template_lib = {path = "../template_lib"}