[package]
name = "lib_test"
version = "0.1.0"
authors = ["Martin Pinholt <mapi@itu.dk>"]
edition = "2018"
repository = "https://github.com/mart368b/foreignc"

[dependencies]
derive_lib = {path = "../derive_lib", version = "0.1.0"}
foreignc = {path = "../../foreignc", version = "0.1.0"}